In [35]:
import pandas as pd
data=pd.read_csv('https://raw.githubusercontent.com/Rajvardhan180/House_Price_Prediction/main/data/Housing.csv')
data.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [36]:
premium_ = data[(data['guestroom'] == "yes") &( data["area"] >3000 )& (data['airconditioning'] == 'yes')]

In [37]:
premium_

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
8,9870000,8100,4,1,2,yes,yes,yes,no,yes,2,yes,furnished
9,9800000,5750,3,2,4,yes,yes,no,no,yes,1,yes,unfurnished
16,9100000,6600,4,2,2,yes,yes,yes,no,yes,1,yes,unfurnished
18,8890000,4600,3,2,2,yes,yes,no,no,yes,2,no,furnished
21,8680000,7155,3,2,1,yes,yes,yes,no,yes,2,no,unfurnished
22,8645000,8050,3,1,1,yes,yes,yes,no,yes,1,no,furnished
23,8645000,4560,3,2,2,yes,yes,yes,no,yes,1,no,furnished
25,8540000,6540,4,2,2,yes,yes,yes,no,yes,2,yes,furnished
26,8463000,6000,3,2,4,yes,yes,yes,no,yes,0,yes,semi-furnished
34,8120000,6840,5,1,2,yes,yes,yes,no,yes,1,no,furnished
38,7962500,6000,3,1,4,yes,yes,no,no,yes,2,no,unfurnished
49,7420000,7440,3,2,1,yes,yes,yes,no,yes,0,yes,semi-furnished
52,7350000,6000,4,2,4,yes,yes,no,no,yes,1,no,furnished
54,7350000,6000,3,2,2,yes,yes,no,no,yes,1,no,semi-furnished
57,7245000,9000,4,2,4,yes,yes,no,no,yes,1,yes,furnished
58,7210000,7680,4,2,4,yes,yes,no,no,yes,1,no,semi-furnished
59,7210000,6000,3,2,4,yes,yes,no,no,yes,1,no,furnished
78,6650000,5700,3,1,1,yes,yes,yes,no,yes,2,yes,furnished
79,6650000,6000,3,2,3,yes,yes,no,no,yes,0,no,furnished
88,6475000,7410,3,1,1,yes,yes,yes,no,yes,2,yes,unfurnished
92,6405000,4800,3,2,4,yes,yes,no,no,yes,0,no,furnished
97,6300000,6400,3,1,1,yes,yes,yes,no,yes,1,yes,semi-furnished
102,6195000,5500,3,2,4,yes,yes,no,no,yes,1,no,semi-furnished
103,6195000,6350,3,2,3,yes,yes,no,no,yes,0,no,furnished
115,6020000,8000,3,1,1,yes,yes,yes,no,yes,2,yes,semi-furnished
117,5950000,3700,4,1,2,yes,yes,no,no,yes,0,no,furnished
121,5950000,7231,3,1,2,yes,yes,yes,no,yes,0,yes,semi-furnished
128,5873000,5500,3,1,3,yes,yes,no,no,yes,1,no,furnished
139,5740000,6360,3,1,1,yes,yes,yes,no,yes,2,yes,furnished
144,5600000,4700,4,1,2,yes,yes,yes,no,yes,1,no,furnished
150,5600000,5136,3,1,2,yes,yes,yes,no,yes,0,yes,unfurnished
152,5565000,5400,5,1,2,yes,yes,yes,no,yes,0,yes,furnished
159,5460000,3150,3,2,1,yes,yes,yes,no,yes,0,no,furnished
160,5460000,6210,4,1,4,yes,yes,no,no,yes,0,no,furnished
161,5460000,6100,3,1,3,yes,yes,no,no,yes,0,yes,semi-furnished
163,5425000,6825,3,1,1,yes,yes,yes,no,yes,0,yes,semi-furnished
172,5250000,8400,3,1,2,yes,yes,yes,no,yes,2,yes,unfurnished
201,4900000,4095,3,1,2,no,yes,yes,no,yes,0,no,semi-furnished
206,4900000,5800,2,1,1,yes,yes,yes,no,yes,0,no,semi-furnished
233,4620000,4160,3,1,1,yes,yes,yes,no,yes,0,no,unfurnished
235,4620000,5680,3,1,2,yes,yes,no,no,yes,1,no,semi-furnished
415,3395000,4785,3,1,2,yes,yes,yes,no,yes,1,no,furnished

In [38]:
result1 = premium_.groupby('furnishingstatus')[['price', 'bedrooms']].mean()

In [39]:
result1

                         price  bedrooms
furnishingstatus
furnished         7.039455e+06  3.545455
semi-furnished    6.170231e+06  3.000000
unfurnished       7.185938e+06  3.125000

In [40]:
data['energy_load'] = ((data['area'] *0.5) + (data['bedrooms'] *0.5))+(data['bathrooms'] *0.5)

In [41]:
data

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus,energy_load
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished,3713.0
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished,4484.0
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished,4982.5
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished,3753.0
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished,3712.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished,1501.5
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished,1202.0
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished,1811.5
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished,1457.0
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished,1927.0

In [43]:
filterd.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus,energy_load
378,3640000,2275,3,1,3,yes,no,no,yes,yes,0,yes,semi-furnished,1139.5

In [44]:
filterd.count()

price               1
area                1
bedrooms            1
bathrooms           1
stories             1
mainroad            1
guestroom           1
basement            1
hotwaterheating     1
airconditioning     1
parking             1
prefarea            1
furnishingstatus    1
energy_load         1
dtype: int64

In [45]:
filterd.groupby('furnishingstatus')[['energy_load' , 'price']] .mean()

                  energy_load      price
furnishingstatus
semi-furnished         1139.5  3640000.0